
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sap.document.sap.soap.functions.mc_style;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-08T14:38:06.607+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "service",
                      portName = "binding",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "file:/Users/hyy/a.xml",
                      endpointInterface = "com.sap.document.sap.soap.functions.mc_style.ZHRJFPERINTERFACE")
                      
public class BindingImpl implements ZHRJFPERINTERFACE {

    private static final Logger LOG = Logger.getLogger(BindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sap.document.sap.soap.functions.mc_style.ZHRJFPERINTERFACE#zdefmHrJfper(com.sap.document.sap.soap.functions.mc_style.TableOfZshrJfpernr  etResult ,)java.lang.String  imDate ,)java.lang.String  imDays ,)com.sap.document.sap.soap.functions.mc_style.TableOfZhrsHtPernr  itPernr )*
     */
    public void zdefmHrJfper(javax.xml.ws.Holder<TableOfZshrJfpernr> etResult,java.lang.String imDate,java.lang.String imDays,javax.xml.ws.Holder<TableOfZhrsHtPernr> itPernr) { 
        LOG.info("Executing operation zdefmHrJfper");
        System.out.println(etResult.value);
        System.out.println(imDate);
        System.out.println(imDays);
        System.out.println(itPernr.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
