
package com.sap.document.sap.soap.functions.mc_style;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-08T14:38:06.624+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class ZHRJFPERINTERFACE_BindingSOAP12_Server{

    protected ZHRJFPERINTERFACE_BindingSOAP12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Binding_SOAP12Impl();
        String address = "http://PKGHDECCP.evergrande.com:8000/sap/bc/srt/rfc/sap/zhr_jfper_interface/800/service/binding";
        Endpoint.publish(address, implementor);
    }
    
//    public static void main(String args[]) throws java.lang.Exception { 
//        new ZHRJFPERINTERFACE_BindingSOAP12_Server();
//        System.out.println("Server ready..."); 
//        
//        Thread.sleep(5 * 60 * 1000); 
//        System.out.println("Server exiting");
//        System.exit(0);
//    }
}
