
package com.sap.document.sap.soap.functions.mc_style;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-08T14:38:06.601+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class ZHRJFPERINTERFACE_BindingSOAP12_Client {

//    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "service");

    private ZHRJFPERINTERFACE_BindingSOAP12_Client() {
    }

//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = Service.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        Service ss = new Service(wsdlURL, SERVICE_NAME);
//        ZHRJFPERINTERFACE port = ss.getBindingSOAP12();  
//        
//        {
//        System.out.println("Invoking zdefmHrJfper...");
//        com.sap.document.sap.soap.functions.mc_style.TableOfZshrJfpernr _zdefmHrJfper_etResultVal = null;
//        javax.xml.ws.Holder<com.sap.document.sap.soap.functions.mc_style.TableOfZshrJfpernr> _zdefmHrJfper_etResult = new javax.xml.ws.Holder<com.sap.document.sap.soap.functions.mc_style.TableOfZshrJfpernr>(_zdefmHrJfper_etResultVal);
//        java.lang.String _zdefmHrJfper_imDate = "";
//        java.lang.String _zdefmHrJfper_imDays = "";
//        com.sap.document.sap.soap.functions.mc_style.TableOfZhrsHtPernr _zdefmHrJfper_itPernrVal = null;
//        javax.xml.ws.Holder<com.sap.document.sap.soap.functions.mc_style.TableOfZhrsHtPernr> _zdefmHrJfper_itPernr = new javax.xml.ws.Holder<com.sap.document.sap.soap.functions.mc_style.TableOfZhrsHtPernr>(_zdefmHrJfper_itPernrVal);
//        port.zdefmHrJfper(_zdefmHrJfper_etResult, _zdefmHrJfper_imDate, _zdefmHrJfper_imDays, _zdefmHrJfper_itPernr);
//
//        System.out.println("zdefmHrJfper._zdefmHrJfper_etResult=" + _zdefmHrJfper_etResult.value);
//        System.out.println("zdefmHrJfper._zdefmHrJfper_itPernr=" + _zdefmHrJfper_itPernr.value);
//
//        }
//
//        System.exit(0);
//    }

}
