package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-08T14:38:06.618+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZHR_JFPER_INTERFACE")
@XmlSeeAlso({ObjectFactory.class})
public interface ZHRJFPERINTERFACE {

    @WebMethod(operationName = "ZdefmHrJfper", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZHR_JFPER_INTERFACE:ZdefmHrJfperRequest")
    @RequestWrapper(localName = "ZdefmHrJfper", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZdefmHrJfper")
    @ResponseWrapper(localName = "ZdefmHrJfperResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZdefmHrJfperResponse")
    public void zdefmHrJfper(
        @WebParam(mode = WebParam.Mode.INOUT, name = "EtResult", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZshrJfpernr> etResult,
        @WebParam(name = "ImDate", targetNamespace = "")
        java.lang.String imDate,
        @WebParam(name = "ImDays", targetNamespace = "")
        java.lang.String imDays,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ItPernr", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZhrsHtPernr> itPernr
    );
}
